"""
FF14 Lovense Bridge v2.1 - Dalamud Edition
Real-time haptic feedback for Final Fantasy XIV using Lovense toys.

Modes:
  1. Dalamud Webhook: Receives events from Triggernometry/PostNamazu plugins
  2. Network Log: Parses FF14/ACT combat logs automatically
  3. Test: Cycles through all event types to test your toys
  4. Demo: Simulates a dungeon run without toys (see what events look like)

Usage:
  python ff14_lovense.py                    # Start (auto-detects mode)
  python ff14_lovense.py --test             # Test vibration patterns
  python ff14_lovense.py --demo             # Simulate events without toys
  python ff14_lovense.py --player "Name"    # Set player name for log parsing
  python ff14_lovense.py --setup            # Interactive setup wizard
  python ff14_lovense.py --port 8069        # Custom webhook port

Repository: https://github.com/SunFlash12/ff14-lovense
Support: https://ko-fi.com/theoneboundinink
"""

import os
import re
import sys
import time
import json
import struct
import threading
import requests
import urllib3
from pathlib import Path
from http.server import HTTPServer, BaseHTTPRequestHandler
from datetime import datetime

# Fix Windows console encoding
import io
if hasattr(sys.stdout, 'buffer'):
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')

urllib3.disable_warnings()

# ============================================================
# CONFIG - Edit these or use local_config.py
# ============================================================
DEFAULT_LOVENSE_DOMAIN = "https://YOUR-LOVENSE-DOMAIN:30010"
DEFAULT_WEBHOOK_PORT = 8069

# Try to load local config
try:
    from local_config import LOVENSE_DOMAIN, TOYS as LOCAL_TOYS
    print("[OK] Loaded local config!")
except ImportError:
    LOVENSE_DOMAIN = os.environ.get("LOVENSE_DOMAIN", DEFAULT_LOVENSE_DOMAIN)
    LOCAL_TOYS = None

# Auto-detected toys (populated on startup)
TOYS = {}

# FF14 log paths
NETWORK_LOG_PATHS = [
    Path.home() / "AppData" / "Roaming" / "Advanced Combat Tracker" / "FFXIVLogs",
    Path.home() / "Documents" / "My Games" / "FINAL FANTASY XIV - A Realm Reborn" / "log",
    Path.home() / "Documents" / "My Games" / "FINAL FANTASY XIV" / "log",
]


# ============================================================
# SETUP WIZARD
# ============================================================
def run_setup():
    """Interactive setup wizard for first-time users."""
    print("\n" + "=" * 55)
    print("  FF14 Lovense Bridge - Setup Wizard")
    print("=" * 55)
    
    print("\n[PHONE] Step 1: Lovense Remote App")
    print("   1. Open Lovense Remote on your phone")
    print("   2. Connect your toy(s)")
    print("   3. Go to: Me -> Game Mode -> Enable")
    print("   4. Note the Local IP shown (e.g., 192.168.1.100)")
    
    ip = input("\n   Enter your Lovense Local IP: ").strip()
    if not ip:
        print("   [!]  No IP entered. You can set LOVENSE_DOMAIN env var later.")
        return
    
    domain = f"https://{ip.replace('.', '-')}.lovense.club:30010"
    print(f"\n   Testing connection to {domain}...")
    
    try:
        r = requests.post(f"{domain}/command", json={"command": "GetToys"}, timeout=5, verify=False)
        data = r.json()
        if data.get("code") == 200:
            toys = json.loads(data["data"]["toys"])
            print(f"   [OK] Connected! Found {len(toys)} toy(s):")
            toy_config = {}
            for tid, t in toys.items():
                print(f"     - {t['name']} ({t['battery']}% battery)")
                toy_config[t['name']] = tid
            
            # Save config
            config = f'''# Local config - auto-generated by setup wizard
# DO NOT COMMIT THIS FILE

LOVENSE_DOMAIN = "{domain}"

TOYS = {json.dumps(toy_config, indent=4)}
'''
            config_path = Path(__file__).parent / "local_config.py"
            config_path.write_text(config)
            print(f"\n   [OK] Config saved to {config_path}")
            print("   [OK] This file is .gitignored and won't be shared")
        else:
            print(f"   [X] Connection failed: {data}")
    except Exception as e:
        print(f"   [X] Could not connect: {e}")
        print("   Make sure Game Mode is ON and you're on the same WiFi")
    
    print("\n[GAME] Step 2: Dalamud/XIVLauncher (Recommended)")
    print("   1. Install XIVLauncher: https://goatcorp.github.io/")
    print("   2. In-game: open Dalamud Settings -> Experimental")
    print("   3. Install 'Triggernometry' plugin")
    print("   4. Add triggers that POST to http://127.0.0.1:8069")
    print("   (See README.md for trigger examples)")
    
    print("\n[NOTE] Step 3: ACT/IINACT (Alternative)")
    print("   If you use ACT, the bridge auto-detects log files")
    print("   Just run the bridge and play -- it reads combat logs")
    
    print("\n[OK] Setup complete! Run: python ff14_lovense.py")


# ============================================================
# LOVENSE CONTROLLER
# ============================================================
class LovenseController:
    def __init__(self, domain):
        self.domain = domain
        self.current_intensity = {}
        self.last_command_time = 0
        self.min_interval = 0.3
        self.connected = False
        self.demo_mode = False
    
    def connect(self):
        if self.demo_mode:
            self.connected = True
            return True
        toys = self.get_toys()
        if toys:
            self.connected = True
            global TOYS
            for tid, t in toys.items():
                TOYS[t["name"].lower()] = tid
                print(f"  [OK] {t['name']}: {tid} ({t['battery']}% battery)")
            return True
        return False
    
    def send(self, toy_id, command):
        if self.demo_mode:
            return {"code": 200}
        now = time.time()
        if now - self.last_command_time < self.min_interval:
            return None
        self.last_command_time = now
        try:
            cmd = {**command, "toy": toy_id or "", "apiVer": 1}
            r = requests.post(f"{self.domain}/command", json=cmd, timeout=3, verify=False)
            return r.json()
        except:
            return None
    
    def vibrate(self, intensity, duration=5, toy=""):
        intensity = max(0, min(20, int(intensity)))
        self.current_intensity[toy] = intensity
        return self.send(toy, {"command": "Function", "action": f"Vibrate:{intensity}", "timeSec": duration})
    
    def pattern(self, strengths, duration=10, toy=""):
        return self.send(toy, {"command": "Pattern", "rule": "V:1;F:v;S:100#", "strength": strengths, "timeSec": duration})
    
    def preset(self, name, duration=10, toy=""):
        return self.send(toy, {"command": "Preset", "name": name, "timeSec": duration})
    
    def stop_all(self):
        self.send("", {"command": "Function", "action": "Vibrate:0", "timeSec": 0})
    
    def get_toys(self):
        try:
            r = requests.post(f"{self.domain}/command", json={"command": "GetToys"}, timeout=5, verify=False)
            data = r.json()
            if data.get("code") == 200:
                return json.loads(data["data"]["toys"])
        except:
            pass
        return {}


# ============================================================
# EVENT MAPPER
# ============================================================
class EventMapper:
    def __init__(self, controller):
        self.ctrl = controller
        self.combo_counter = 0
        self.last_event = None
        self.last_event_time = 0
        self.player_hp_pct = 100
        self.in_combat = False
    
    def get_toy(self, name):
        """Get toy ID by name, case-insensitive."""
        return TOYS.get(name.lower(), TOYS.get(name, ""))
    
    def handle(self, event_type, value=0, **kwargs):
        now = time.time()
        if event_type == self.last_event and now - self.last_event_time < 2:
            self.combo_counter = min(self.combo_counter + 1, 8)
        else:
            self.combo_counter = 0
        self.last_event = event_type
        self.last_event_time = now
        combo = self.combo_counter * 2
        
        # Get first available toy for each slot
        all_toys = list(TOYS.values())
        toy1 = all_toys[0] if len(all_toys) > 0 else ""
        toy2 = all_toys[1] if len(all_toys) > 1 else ""
        toy3 = all_toys[2] if len(all_toys) > 2 else ""
        
        # ---- COMBAT ----
        if event_type == "damage_taken":
            damage = value
            max_hp = kwargs.get("max_hp", 50000)
            pct = min(100, (damage / max(1, max_hp)) * 100)
            intensity = min(20, max(3, int(pct / 5) + 3 + combo))
            print(f"  [COMBAT]  Damage: {damage} ({pct:.0f}% HP) -> intensity {intensity}")
            self.ctrl.vibrate(intensity, 2, toy1)
            if pct > 20:
                self.ctrl.vibrate(min(intensity - 3, 15), 2, toy2)
        
        elif event_type == "damage_dealt":
            intensity = min(8, max(2, value // 10000 + 2))
            print(f"  [HIT] Dealt: {value} -> {intensity}")
            self.ctrl.vibrate(intensity, 1, toy2)
        
        elif event_type == "hp_update":
            hp_pct = value
            self.player_hp_pct = hp_pct
            if hp_pct < 30:
                print(f"  [HP]  HP CRITICAL: {hp_pct}%")
                self.ctrl.vibrate(16 + combo, 3, toy1)
            elif hp_pct < 50:
                print(f"  [HP] HP LOW: {hp_pct}%")
                self.ctrl.vibrate(12, 3, toy1)
        
        elif event_type == "death":
            print(f"  [DEAD] DEATH -> full burst then silence")
            self.ctrl.vibrate(20, 1)
            time.sleep(1.5)
            self.ctrl.stop_all()
        
        elif event_type == "raise":
            print(f"  [UP] Raised!")
            self.ctrl.pattern("0;5;10;15;10;5;0;5;10;15;20", 5)
        
        elif event_type == "heal_received":
            intensity = min(10, max(2, value // 5000 + 2))
            print(f"  [HEAL] Healed: {value} -> gentle {intensity}")
            self.ctrl.pattern("3;5;7;5;3", 3, toy1)
        
        elif event_type == "limit_break":
            level = kwargs.get("level", 1)
            print(f"  [LB] LIMIT BREAK L{level} -> MAX POWER")
            self.ctrl.vibrate(20, 5 + level * 3)
        
        elif event_type == "tankbuster":
            print(f"  [TANK]  TANKBUSTER")
            self.ctrl.vibrate(20, 3, toy1)
            self.ctrl.vibrate(15, 3, toy2)
        
        elif event_type == "boss_cast":
            name = kwargs.get("name", "???")
            print(f"  [FIRE] Boss casting: {name}")
            self.ctrl.pattern("5;10;15;18;20;20;20", 5, toy1)
        
        elif event_type == "aoe_warning":
            print(f"  [AOE] AOE WARNING")
            self.ctrl.pattern("0;8;15;8;0;8;15;8;0", 3, toy1)
        
        elif event_type == "stack_marker":
            print(f"  [STACK] Stack marker!")
            self.ctrl.pattern("5;8;11;14;17;20", 3)
        
        elif event_type == "enrage":
            print(f"  [DEAD][FIRE] ENRAGE -> EVERYTHING MAX")
            for t in all_toys:
                self.ctrl.vibrate(20, 30, t)
        
        elif event_type == "duty_complete":
            print(f"  [WIN] DUTY COMPLETE!")
            self.ctrl.preset("fireworks", 15)
        
        elif event_type == "wipe":
            print(f"  [DEAD][DEAD] WIPE")
            self.ctrl.stop_all()
        
        elif event_type == "combat_start":
            self.in_combat = True
            print(f"  [COMBAT]  Combat started")
            self.ctrl.vibrate(3, 10, toy1)
        
        elif event_type == "combat_end":
            self.in_combat = False
            print(f"  [PEACE]  Combat ended")
            self.ctrl.pattern("5;3;2;1;0", 5)
        
        # ---- EMOTES ----
        elif event_type == "emote":
            emote = kwargs.get("name", "")
            emote_responses = {
                "hug":      ("[HUG]", "5;8;10;8;5;3", 5),
                "kiss":     ("[KISS]", "3;5;8;12;15;18;15;12;8;5", 8),
                "pet":      ("[PET]", "4;6;4;6;4", 4),
                "slap":     ("[SLAP]", None, 0),
                "spank":    ("[SPANK]", None, 0),
                "dance":    ("[DANCE]", None, 0),
                "dote":     ("[LOVE]", "5;8;10;12;10;8;5", 6),
                "comfort":  ("[HEART]", "3;5;7;5;3;5;7;5;3", 8),
                "blowkiss": ("[BLOWKISS]", "5;10;15;10;5", 5),
            }
            if emote in emote_responses:
                emoji, pat, dur = emote_responses[emote]
                print(f"  {emoji} Emote: /{emote}")
                if emote == "slap":
                    self.ctrl.vibrate(18, 1)
                elif emote == "spank":
                    self.ctrl.vibrate(20, 1)
                    time.sleep(1)
                    self.ctrl.pattern("0;15;0;15;0;15", 5)
                elif emote == "dance":
                    self.ctrl.preset("wave", 15)
                elif pat:
                    self.ctrl.pattern(pat, dur)
        
        # ---- ERP/CHAT ----
        elif event_type == "chat_trigger":
            ktype = kwargs.get("keyword_type", "mild")
            responses = {
                "mild":    (8,  "[HOT]",   "mild"),
                "intense": (15, "[HOT][HOT]",  "intense"),
                "climax":  (20, "[!!!]",   "CLIMAX"),
                "tease":   (10, "[TEASE]",   "tease"),
                "rough":   (18, "[HIT]",   "rough"),
            }
            if ktype in responses:
                intensity, emoji, label = responses[ktype]
                print(f"  {emoji} ERP: {label}")
                if ktype == "climax":
                    for t in all_toys:
                        self.ctrl.vibrate(20, 15, t)
                elif ktype == "tease":
                    self.ctrl.pattern("5;8;12;15;18;15;12;8;5;0;0;0;5;8;12;15;18;20", 15, toy1)
                elif ktype == "rough":
                    self.ctrl.preset("earthquake", 8, toy1)
                else:
                    self.ctrl.vibrate(min(20, intensity + combo), 5, toy1)
                    self.ctrl.vibrate(min(15, intensity // 2 + combo), 5, toy2)
        
        # ---- ZONE/MISC ----
        elif event_type == "zone_change":
            zone = kwargs.get("zone", "")
            print(f"  [MAP]  Zone: {zone}")
            self.ctrl.vibrate(3, 2)
        
        elif event_type == "cutscene_start":
            print(f"  [SCENE] Cutscene")
            self.ctrl.vibrate(2, 30)
        
        elif event_type == "cutscene_end":
            self.ctrl.stop_all()


# ============================================================
# WEBHOOK SERVER
# ============================================================
class WebhookHandler(BaseHTTPRequestHandler):
    mapper = None
    
    def do_POST(self):
        content_length = int(self.headers.get('Content-Length', 0))
        body = self.rfile.read(content_length).decode('utf-8')
        try:
            data = json.loads(body)
            event_type = data.get("event", data.get("type", ""))
            value = data.get("value", data.get("amount", 0))
            if self.mapper and event_type:
                self.mapper.handle(event_type, value, **data)
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.end_headers()
            self.wfile.write(b'{"ok":true}')
        except Exception as e:
            self.send_response(400)
            self.end_headers()
            self.wfile.write(str(e).encode())
    
    def do_GET(self):
        """Health check / status endpoint."""
        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.end_headers()
        status = {
            "status": "running",
            "version": "2.1",
            "toys_connected": len(TOYS),
            "toys": list(TOYS.keys()),
            "events_supported": [
                "damage_taken", "damage_dealt", "hp_update", "death", "raise",
                "heal_received", "limit_break", "tankbuster", "boss_cast",
                "aoe_warning", "stack_marker", "enrage", "duty_complete", "wipe",
                "combat_start", "combat_end", "emote", "chat_trigger",
                "zone_change", "cutscene_start", "cutscene_end"
            ]
        }
        self.wfile.write(json.dumps(status, indent=2).encode())
    
    def log_message(self, format, *args):
        pass


# ============================================================
# NETWORK LOG PARSER
# ============================================================
class NetworkLogParser:
    """Parse FF14 ACT/IINACT network logs."""
    
    ERP_KEYWORDS = {
        "mild": ["moan", "gasp", "whimper", "pant", "shiver", "tremble", "blush"],
        "intense": ["thrust", "pound", "stroke", "grind", "ride", "bounce", "harder"],
        "climax": ["cum", "orgasm", "climax", "finish", "release"],
        "tease": ["tease", "edge", "deny", "beg", "plead", "slowly"],
        "rough": ["spank", "slap", "choke", "grab", "pull", "pin", "force"],
    }
    
    EMOTE_KEYWORDS = {
        "hug": ["hugs", "embraces"], "kiss": ["kisses"],
        "pet": ["pets", "pats"], "slap": ["slaps"],
        "spank": ["spanks"], "dance": ["dances"], "dote": ["dotes"],
    }
    
    def __init__(self, mapper):
        self.mapper = mapper
        self.player_name = None
    
    def parse_line(self, line):
        parts = line.strip().split("|")
        if len(parts) < 3:
            return
        
        opcode = parts[0]
        
        if opcode == "00" and len(parts) > 4:  # Chat
            msg = parts[4].lower() if len(parts) > 4 else ""
            for ktype, keywords in self.ERP_KEYWORDS.items():
                if any(kw in msg for kw in keywords):
                    self.mapper.handle("chat_trigger", keyword_type=ktype)
                    return
            for emote, keywords in self.EMOTE_KEYWORDS.items():
                if any(kw in msg for kw in keywords):
                    self.mapper.handle("emote", name=emote)
                    return
        
        elif opcode in ("15", "16") and len(parts) > 9:  # Ability
            try:
                target = parts[7] if len(parts) > 7 else ""
                source = parts[3] if len(parts) > 3 else ""
                damage = int(parts[9], 16) if parts[9] else 0
                if damage > 0:
                    if self.player_name and target == self.player_name:
                        self.mapper.handle("damage_taken", damage)
                    elif self.player_name and source == self.player_name:
                        self.mapper.handle("damage_dealt", damage)
            except:
                pass
        
        elif opcode == "25" and len(parts) > 3:  # Death
            if self.player_name and parts[3] == self.player_name:
                self.mapper.handle("death")
        
        elif opcode == "21" and len(parts) > 5:  # Cast start
            source = parts[3] if len(parts) > 3 else ""
            ability = parts[5] if len(parts) > 5 else ""
            if self.player_name and source != self.player_name:
                self.mapper.handle("boss_cast", name=ability)


# ============================================================
# DEMO MODE
# ============================================================
def run_demo():
    """Simulate a dungeon run to show what the bridge does."""
    print("\n" + "=" * 55)
    print("  FF14 Lovense Bridge - DEMO MODE")
    print("  (No toys needed - shows event detection)")
    print("=" * 55)
    
    ctrl = LovenseController(DEFAULT_LOVENSE_DOMAIN)
    ctrl.demo_mode = True
    ctrl.connect()
    mapper = EventMapper(ctrl)
    
    scenarios = [
        ("\n--- Entering Dungeon ---", "zone_change", 0, {"zone": "Sastasha"}),
        ("Pulling first pack...", "combat_start", 0, {}),
        ("Tank takes a hit!", "damage_taken", 8000, {"max_hp": 50000}),
        ("Healer patches you up", "heal_received", 12000, {}),
        ("You land a crit!", "damage_dealt", 25000, {}),
        ("Another hit!", "damage_taken", 15000, {"max_hp": 50000}),
        ("Combo! More damage incoming!", "damage_taken", 20000, {"max_hp": 50000}),
        ("Pack cleared!", "combat_end", 0, {}),
        ("", None, 2, {}),
        ("\n--- Boss Fight: Denn the Orcatoothed ---", "combat_start", 0, {}),
        ("Boss starts casting Hydroball!", "boss_cast", 0, {"name": "Hydroball"}),
        ("AOE marker on you!", "aoe_warning", 0, {}),
        ("TANKBUSTER incoming!", "tankbuster", 0, {}),
        ("HP dropping fast!", "hp_update", 25, {}),
        ("Big heal saves you!", "heal_received", 30000, {}),
        ("Someone uses /kiss on you during the fight!", "emote", 0, {"name": "kiss"}),
        ("Boss is enraging!!", "enrage", 0, {}),
        ("LIMIT BREAK 3!!!", "limit_break", 0, {"level": 3}),
        ("", None, 3, {}),
        ("[WIN] DUTY COMPLETE!", "duty_complete", 0, {}),
        ("", None, 2, {}),
        ("\n--- Back in Town ---", "zone_change", 0, {"zone": "Limsa Lominsa"}),
        ("Someone /hugs you", "emote", 0, {"name": "hug"}),
        ("Someone /dotes on you", "emote", 0, {"name": "dote"}),
        ("", None, 2, {}),
        ("\n--- ERP Scene ---", "chat_trigger", 0, {"keyword_type": "mild"}),
        ("Things are heating up...", "chat_trigger", 0, {"keyword_type": "intense"}),
        ("Getting teased...", "chat_trigger", 0, {"keyword_type": "tease"}),
        ("!!!", "chat_trigger", 0, {"keyword_type": "climax"}),
    ]
    
    for desc, event, value, kwargs in scenarios:
        if desc:
            print(f"\n{desc}")
        if event is None:
            time.sleep(value)
            continue
        mapper.handle(event, value, **kwargs)
        time.sleep(1.5)
    
    print("\n\n" + "=" * 55)
    print("  Demo complete! With real toys connected,")
    print("  each event triggers vibration patterns.")
    print("=" * 55)


# ============================================================
# MAIN
# ============================================================
def main():
    # Parse args
    if "--setup" in sys.argv:
        run_setup()
        return
    
    if "--demo" in sys.argv:
        run_demo()
        return
    
    port = DEFAULT_WEBHOOK_PORT
    if "--port" in sys.argv:
        idx = sys.argv.index("--port") + 1
        if idx < len(sys.argv):
            port = int(sys.argv[idx])
    
    print("=" * 55)
    print("  FF14 Lovense Bridge v2.1 - Dalamud Edition")
    print("  https://github.com/SunFlash12/ff14-lovense")
    print("=" * 55)
    
    ctrl = LovenseController(LOVENSE_DOMAIN)
    
    # Test mode
    if "--test" in sys.argv:
        print("\nConnecting to Lovense...")
        if not ctrl.connect():
            print("\n[!]  No toys found!")
            print("Make sure Lovense Remote is open with Game Mode ON.")
            print("Run --setup for first-time configuration.")
            return
        
        print("\n=== TEST MODE ===")
        mapper = EventMapper(ctrl)
        tests = [
            ("[COMBAT]  Testing damage taken...",  "damage_taken", 15000, {"max_hp": 50000}),
            ("[HEAL] Testing heal...",           "heal_received", 10000, {}),
            ("[FIRE] Testing boss cast...",      "boss_cast", 0, {"name": "Megaflare"}),
            ("[KISS] Testing kiss emote...",      "emote", 0, {"name": "kiss"}),
            ("[LB] Testing limit break L3...", "limit_break", 0, {"level": 3}),
            ("[WIN] Testing victory...",        "duty_complete", 0, {}),
        ]
        for desc, evt, val, kw in tests:
            print(f"\n{desc}")
            mapper.handle(evt, val, **kw)
            time.sleep(4)
        ctrl.stop_all()
        print("\n[OK] Test complete!")
        return
    
    # Normal mode
    print("\nConnecting to Lovense...")
    if not ctrl.connect():
        print("\n[!]  No toys found!")
        print("Options:")
        print("  1. Run --setup for first-time configuration")
        print("  2. Run --demo to see how it works without toys")
        print("  3. Make sure Lovense Remote app has Game Mode ON")
        return
    
    mapper = EventMapper(ctrl)
    
    # Start webhook server
    print(f"\n[WEB] Starting webhook server on port {port}...")
    WebhookHandler.mapper = mapper
    server = HTTPServer(("127.0.0.1", port), WebhookHandler)
    server_thread = threading.Thread(target=server.serve_forever, daemon=True)
    server_thread.start()
    print(f"   Webhook: http://127.0.0.1:{port}")
    print(f"   Status:  http://127.0.0.1:{port} (GET)")
    
    # Find player name
    player_name = None
    if "--player" in sys.argv:
        idx = sys.argv.index("--player") + 1
        if idx < len(sys.argv):
            player_name = sys.argv[idx]
    
    # Start log parser
    log_parser = NetworkLogParser(mapper)
    log_parser.player_name = player_name
    
    log_file = None
    for log_dir in NETWORK_LOG_PATHS:
        if log_dir.exists():
            files = sorted(log_dir.glob("*.log"), key=os.path.getmtime, reverse=True)
            if files:
                log_file = files[0]
                break
    
    if player_name:
        print(f"\n[PLAYER] Player: {player_name}")
    if log_file:
        print(f"[LOG] Log: {log_file.name}")
    else:
        print("[LOG] No log file found (waiting for FF14 to start)")
    
    print("\n" + "=" * 55)
    print("  [OK] READY! Play FF14 and feel the game!")
    print("  Press Ctrl+C to stop")
    print("=" * 55 + "\n")
    
    try:
        if log_file:
            with open(log_file, 'r', encoding='utf-8', errors='ignore') as f:
                f.seek(0, 2)
                while True:
                    line = f.readline()
                    if line:
                        log_parser.parse_line(line)
                    else:
                        time.sleep(0.05)
        else:
            while True:
                time.sleep(1)
    except KeyboardInterrupt:
        print("\nStopping toys...")
        ctrl.stop_all()
        server.shutdown()
        print("Bye! :)")


if __name__ == "__main__":
    main()



